# Generated by Django 5.0.7 on 2024-07-16 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='start_at',
        ),
    ]
